language: java
os: linux
jdk: openjdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2 
addons:
  update: true
  apt:
    packages:
      - maven
      - libcppunit-dev
  sonarcloud:
    organization: "cesto93"
    token: $SONAR_TOKEN  
script:
  - mvn clean verify -Pfull-build
  - mvn sonar:sonar -Pcoverage -Dsonar.projectKey=$PROJECT_KEY
  
#script: mvn -X clean apache-rat:check verify spotbugs:check checkstyle:check -Pfull-build
