language: java
os: linux
jdk: openjdk8
addons:
  update: true
  apt:
    packages:
      - maven
      - libcppunit-dev
  sonarcloud:
    organization: "cesto93"
    token: $SONAR_TOKEN  
script:
  - mvn clean install -Pfull-build sonar:sonar -Pcoverage -Dsonar.projectKey=$PROJECT_KEY
  
#script: mvn -X clean apache-rat:check verify spotbugs:check checkstyle:check -Pfull-build
