language: java
sudo: false

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk11
    - os: linux
      arch: s390x
      jdk: openjdk11
      addons:
        apt:
          update: true
          packages:
            - maven
            - libcppunit-dev

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev
  sonarcloud:
    organization: "cesto93"
    token: $SONAR_TOKEN

#script: mvn clean apache-rat:check verify spotbugs:check checkstyle:check -Pfull-build
script:
  - mvn clean verify install sonar:sonar -Pcoverage -Dsonar.projectKey=$PROJECT_KEY -Dsonar.java.binaries=.
