language: java
sudo: false
os: linux
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2"
addons:
  apt:
    packages:
    - libcppunit-dev
  sonarcloud:
    organization: "cesto93"
    token: $SONAR_TOKEN
script:
  - mvn clean apache-rat:check verify spotbugs:check checkstyle:check -Pfull-build install sonar:sonar -Pcoverage -Dsonar.projectKey=$PROJECT_KEY -Dsonar.java.binaries=.
  
#script: mvn clean apache-rat:check verify spotbugs:check checkstyle:check -Pfull-build
